# Site
name: "CTS"
title: "Cement tile"
description: "We are those who love and preserve Vietnamese culture, we had concerns and looked for a way to recover traditional cement tile products."
logo: 'assets/images/logo dai.png'
favicon: 'assets/images/logo cts1.png'
baseurl: /blogcementtile
google_analytics: 'UA-xxxxxxxx-1'
disqus: 'demowebsite'
include: ["_pages"]
permalink: /:title/
email: cts@cementtile.vn

# Authors
authors:
  sal:
    name: CTS
    display_name: CTS
    avatar: 'assets/images/logo cts1.png'
    email: cts@cementtile.vn
    web: https://nguyensoncavn.com/
    twitter: https://www.twitter.com/vietnamtiles
    description: "We had concerns and looked for a way to recover traditional cement tile products."
  john:
    name: By CTS
    display_name: By CTS    
    avatar: 'assets/images/logo cts1.png'
    email: cts@cementtile.vn
    web: https://nguyensoncavn.com/
    twitter: https://www.twitter.com/vietnamtiles
    description: "We had concerns and looked for a way to recover traditional cement tile products."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
highlighter: none
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true



# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "enabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
